### ISSUE TITLE
Any release for ROS Melodic

### ISSUE THREAD

**Issue by ibrahimqazi** [pulver22/ardrone_tf_controller#3]
The present version does not work in Ubuntu 18.04 Melodic environment. Do you have any plan to update the repository?

**Comment by pulver22** [comment]
Hi @ibrahimqazi,

This code was not tested against ubuntu 18 and ros melodic. I assume you get some compilation errors. I can try and see how much effort it requires to being updated but I cannot guarantee you I will do it soon.

In the meantime, if you need a quadcopter simulator, I can suggest you to have a look at this my other repository [QLab](https://github.com/pulver22/QLAB). It doesn't contain an additional platform like a UGV or a USV but you should be able to simply copy paste the imporant file from the current repository to the other one.


Please, let me know if you need any other help!

**Comment by ibrahimqazi** [comment]
Hello @pulver22 and greatly appreciate your response. There are plenty of errors, it starts from no availability of ardrone package. The problem is ardrone package itself doesnt work with melodic. There might be more errors as well. I will try add other drone platform but it will take time as I am not very good in ROS :). In the meantime if there is any updates from your side that will great also.
Thank you once again.
